import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {CssBaseline, StyledEngineProvider} from "@mui/material";
import React from "react";
import {createTheme, ThemeProvider} from "@mui/material/styles";


const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

interface chid {
    children: React.ReactNode
}

export default function RootLayout({children}: chid) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <StyledEngineProvider injectFirst>
            {children}
        </StyledEngineProvider>
        </body>
        </html>
    )
}
